### PR TITLE
Managing the development process scrum vs. kanban

### PR DESCRIPTION
**Pull request by jlee15**

### CODE REVIEW

**Comment by rrw708** [comment]
nice work @jlee15 . It might be helpful to give one example of when a sprint is ideal. Otherwise looks great.

**Comment by Branlund** [comment]
Nice comparison here @jlee15, you could also add in the last paragraph that another strong differentiating factor is that Kanban allows for a flexible to-do list where newly created stories can be quickly added and prioritized.

**Comment by nennis15** [comment]
Great work @jlee15 . Maybe just add in a sentence describing which process is ultimately more cost effective.

**Comment by jlee15** [comment]
Awesome guys! @rrw708 I added in more detail in the first paragraph on the types of projects better suited for Scrum sprints.  @Branlund I incorporated your suggestion on Kanban's flexibility at the end of the second paragraph.  And @nennis15 I added at the end of the page additional color on the cost effectiveness typically of Kanban over Scrum.

If all are ok send over your :+1 's!

**Comment by nennis15** [comment]
Good to ship! :+1:

**Comment by Branlund** [comment]
Awesome, :+1:  to ship!

**Comment by rrw708** [comment]
:+1 Kobe!

**Comment by rrw708** [comment]
Crap it didn't work. :+1:

**Pull request merged**
