### PR TITLE
Communicating your intent to developers

### PR DESCRIPTION
**Pull request by nennis15**
Let me know what you think @rrw707 @branlund @jlee15

### CODE REVIEW

**Comment by Branlund** [comment]
Great work @nennis15, you could also add in the second paragraph that another effective way of communicating is providing a mock prototype or picture of the desired app/functionality.

**Comment by jlee15** [comment]
Awesome @nennis15 . One of my high level takeaways is that the manager should set the parameters for the end product but let the developer fill in the details on how best to do/achieve it.  Perhaps you could add this in at the end of the first paragraph

**Comment by rrw708** [comment]
Nice stuff, @nennis15 . It might be useful to mention how a developer should be able to communicate your vision back to you.

**Comment by nennis15** [comment]
Thanks a lot @jlee15 @Branlund @rrw708 ! All feedback has been incorporated. Let me know if it's :+1: to ship!

**Comment by Branlund** [comment]
Good :+1:  to ship!

**Comment by rrw708** [comment]
:+1:

**Comment by jlee15** [comment]
Good to go :+1:

**Pull request merged**
