### PR TITLE
Keep your expectations conservative when developing software

### PR DESCRIPTION
**Pull request by rrw708**

### CODE REVIEW

**Comment by rrw708** [comment]
thanks @Branlund . I just updated. Check out the "Files changed" tab above to see my modifications and let me know if its good to go!

**Comment by jlee15** [comment]
awesome @rrw708 - another takeaway I had was during initial discussions with developers, in the context of user stories, just mention the "role" and "benefit" parts and task the developer with determining how best to develop the "feature" part.

**Comment by rrw708** [comment]
Thanks @Branlund and @jlee15 . All changes are implemented. Hope I'm good to ship. Keep those :+1: coming!

**Comment by jlee15** [comment]
:+1: @rrw708

**Comment by nennis15** [comment]
Great stuff @rrw708. I would add in something that speaks to the benefits of paying your developer by the hour rather than a fixed cost.

**Comment by nennis15** [comment]
Good to ship! :+1:

**Comment by rrw708** [comment]
thanks all. I've updated and will merge shortly.

**Pull request merged**
