### PR TITLE
How to write effective user stories

### PR DESCRIPTION
**Pull request by Branlund**
Let me know what you think @rrw707 @nennis15 @jlee15, thanks guys!

### CODE REVIEW

**Comment by rrw708** [comment]
Good stuff, @Branlund . My only comment would be to briefly mention that "features" can be told from a different perspective "role" , helping the developer see the big picture.

**Comment by jlee15** [comment]
Looks good @Branlund, one suggestion is to mention using the back of user story cards to write down the acceptance criteria in order to validate that the user story has been implemented correctly

**Comment by rrw708** [comment]
:+1:

**Comment by nennis15** [comment]
Good stuff @Branlund. I would just add something about making sure that the benefit of the user story really does benefit the end user and isn't only a benefit for the company making the app (i.e. the end user doesn't care if a retailer's app makes the ordering process cheaper for the retailer).

**Comment by Branlund** [comment]
I just incorporated all feedback, give me a :+1: if good to ship!

**Comment by jlee15** [comment]
Great job @Branlund ! :+1:

**Comment by nennis15** [comment]
Good to ship :+1:

**Pull request merged**
